<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>FFXIV_ACT_Plugin</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="costura.machina.dll.compressed" />
    <None Remove="costura.machina.ffxiv.dll.compressed" />
    <None Remove="costura.newtonsoft.json.dll.compressed" />
    <None Remove="costura.ffxiv_act_plugin.common.dll.compressed" />
    <None Remove="costura.ffxiv_act_plugin.config.dll.compressed" />
    <None Remove="costura.ffxiv_act_plugin.logfile.dll.compressed" />
    <None Remove="costura.ffxiv_act_plugin.memory.dll.compressed" />
    <None Remove="costura.ffxiv_act_plugin.network.dll.compressed" />
    <None Remove="costura.ffxiv_act_plugin.parse.dll.compressed" />
    <None Remove="costura.ffxiv_act_plugin.resource.dll.compressed" />
    <EmbeddedResource Include="costura.machina.dll.compressed" LogicalName="costura.machina.dll.compressed" />
    <EmbeddedResource Include="costura.machina.ffxiv.dll.compressed" LogicalName="costura.machina.ffxiv.dll.compressed" />
    <EmbeddedResource Include="costura.newtonsoft.json.dll.compressed" LogicalName="costura.newtonsoft.json.dll.compressed" />
    <EmbeddedResource Include="costura.ffxiv_act_plugin.common.dll.compressed" LogicalName="costura.ffxiv_act_plugin.common.dll.compressed" />
    <EmbeddedResource Include="costura.ffxiv_act_plugin.config.dll.compressed" LogicalName="costura.ffxiv_act_plugin.config.dll.compressed" />
    <EmbeddedResource Include="costura.ffxiv_act_plugin.logfile.dll.compressed" LogicalName="costura.ffxiv_act_plugin.logfile.dll.compressed" />
    <EmbeddedResource Include="costura.ffxiv_act_plugin.memory.dll.compressed" LogicalName="costura.ffxiv_act_plugin.memory.dll.compressed" />
    <EmbeddedResource Include="costura.ffxiv_act_plugin.network.dll.compressed" LogicalName="costura.ffxiv_act_plugin.network.dll.compressed" />
    <EmbeddedResource Include="costura.ffxiv_act_plugin.parse.dll.compressed" LogicalName="costura.ffxiv_act_plugin.parse.dll.compressed" />
    <EmbeddedResource Include="costura.ffxiv_act_plugin.resource.dll.compressed" LogicalName="costura.ffxiv_act_plugin.resource.dll.compressed" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="System.Core">
      <HintPath>../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Advanced Combat Tracker" />
    <Reference Include="FFXIV_ACT_Plugin.Parse" />
    <Reference Include="FFXIV_ACT_Plugin.Common" />
    <Reference Include="FFXIV_ACT_Plugin.Config" />
    <Reference Include="System.Windows.Forms.DataVisualization" />
    <Reference Include="FFXIV_ACT_Plugin.Logfile" />
    <Reference Include="FFXIV_ACT_Plugin.Memory" />
    <Reference Include="FFXIV_ACT_Plugin.Network" />
    <Reference Include="System.Xml">
      <HintPath>../../../../usr/share/dotnet/shared/Microsoft.NETCore.App/6.0.25/System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="Machina.FFXIV" />
    <Reference Include="FFXIV_ACT_Plugin.Resource" />
    <Reference Include="Machina" />
  </ItemGroup>
</Project>